### ISSUE TITLE
docs: output format

### ISSUE THREAD

**Issue by phmLabs** [startwind/forrest#111]
```yaml
  'file:length':
      name: 'file:length'
      description: 'Return the number of lines of a given file.'
      output-format: The file has %s lines.
      prompt: 'cat ${filename} | wc -l'
```
