### ISSUE TITLE
Add `prefix` and `postfix` as parameter options

### ISSUE THREAD

**Issue by phmLabs** [startwind/forrest#138]
```yaml
parameters:
    password:
        optional: true
        type: forrest_password
        prefix: '-p '
```

This example will add the prefix `-p` to the parameter if it is set. 

Needed for this:
```yaml
prompt: mysql -e "CREATE DATABASE ${database_name};" ${password};
```
