### ISSUE TITLE
`command:run` add enum as parameter hints

### ISSUE THREAD

**Issue by phmLabs** [startwind/forrest#24]
It should be possible to have a predefined `enum` for prompt.

```yml
parameters:
  environment:
    enum: 
      - stage
      - production
      - development
```
