### ISSUE TITLE
Repository: Standard repo

### ISSUE THREAD

**Issue by phmLabs** [startwind/forrest#6]
Create a standard repo that is always installed and can't be uninstalled.

**Comment by phmLabs** [comment]
```yaml
  forrest-linux:
    adapter: yaml
    name: 'Forrest Linux Repository'
    description: 'Some very helpful everyday Linux commands.'
    config:
      file: 'https://raw.githubusercontent.com/startwind/forrest-directory/main/repositories/forrest-linux.yml'
```
