### ISSUE TITLE
Parameter default value

### ISSUE THREAD

**Issue by sebastianneubert** [startwind/forrest#69]
sometimes you have a parameter, which may have a default value (ex empty string for a filter)

```yaml
  list-services:
    name: "list:services"
    description: "List all services available for auto-wiring"
    prompt: "php bin/console debug:autowiring ${searchString}"
    parameters:
      searchString:
        name: searchString
        description: Optional search parameter to restrict the search
        default: ""
```

- if parameter entered nothing for the parameter, the default value is used
