### ISSUE TITLE
Repository contraints

### ISSUE THREAD

**Issue by phmLabs** [startwind/forrest#87]
Some repositories should be activated if special constraint is fulfilled. For example if a `-git` file is found the `git command repo`is loaded.

```yaml
repository:
  name: Git commands
  contraints:
    file-exists: .git
```
